# Generated by Django 3.2.9 on 2021-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211123_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='scopearticle',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
